stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running tests..."
  after_script:
    - echo "Cleaning up temporary files..."

run_lnit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
    - chmod +x myscript.sh
  script:
    - ./myscript.sh
  after_script:
    - echo "Cleaning up temporary files..."

build_image:
  only:
    - main
  stage: build
  script:
    - echo "Building docker image..."
    - ehco "Tagging the image..."

push_image:
  only:
    - main
  stage: build
  needs:
    - build_image
  script:
    - echo "Logging into docker registery..."
    - echo "Pushing docker image to registery..."

deploy_image:
  only:
    - main
  stage: deploy
  script:
    - echo "Deploying..."